# Generated by Django 5.1.1 on 2024-11-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_daysduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='deadlineInDays',
            field=models.PositiveBigIntegerField(),
        ),
    ]
