# Generated by Django 5.1.1 on 2024-11-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='taxId',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='identification',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='phoneNumber',
            field=models.PositiveBigIntegerField(),
        ),
    ]
