# Generated by Django 5.1.1 on 2024-11-14 16:56

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_chat_chatname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatName',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
    ]
